const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_COND: 'GET_ALL_COND',
    GET_ALL_INSTR: 'GET_ALL_INSTR',
    GET_ALL_ADMIN: 'GET_ALL_ADMIN',
    GET_MY_EVENTS: 'GET_MY_EVENTS',
    GET_MY_COMPTE: 'GET_MY_COMPTE',
    GET_USER_DET:'GET_USER_DET',
    GET_MY_FORMATIONS: 'GET_MY_FORMATIONS',
    GET_MY_FORMATION: 'GET_MY_FORMATION',
    GET_ALL_FORMATIONS:'GET_ALL_FORMATIONS',
    GET_ALL_ChAP: 'GET_ALL_ChAP',
    GET_ALL_LECON: 'GET_ALL_LECON',
    GET_ALL_CATEGORIE:'GET_ALL_CATEGORIE',
    GET_ALL_SOUS_CATEGORIE:'GET_ALL_SOUS_CATEGORIE',
}

export default ACTIONS
