const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_COND: 'GET_ALL_COND',
    GET_ALL_INSTR: 'GET_ALL_INSTR',
    GET_MY_EVENTS: 'GET_MY_EVENTS',
    GET_MY_COMPTE: 'GET_MY_COMPTE',
    GET_MY_FORMATIONS: 'GET_MY_FORMATIONS',
    GET_MY_FORMATION: 'GET_MY_FORMATION',


}

export default ACTIONS
